version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ['*']
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      development:
        dependency-type: development
  - package-ecosystem: gradle
    directory: /jvm
    schedule:
      interval: weekly
